apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-3gxpxa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3gxpxa
  namespace: my-nginx-3gxpxa
  labels:
    name: nginx-3gxpxa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-3gxpxa
  template:
    metadata:
      namespace: my-nginx-3gxpxa
      labels:
        name: nginx-3gxpxa
    spec:
      containers:
      - name: nginx-3gxpxa
        image: nginx
        ports:
        - containerPort: 80

